---
# Specify local paths of BNCDE and TE-CDE model. Specify prediction window


bncde_path: './epoch=93-step=14758.ckpt'

informative_sampling: False

window: 'one_step'

# window is specified via 'one_step', 'two_step', 'three_step', 'four_step', 'five_step'

...